# Generated by Django 5.0.6 on 2024-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('experiences', models.TextField()),
                ('skills', models.TextField()),
                ('hobbies', models.TextField()),
                ('languages', models.CharField(max_length=50)),
                ('social_accounts', models.TextField()),
            ],
        ),
    ]
